version: '3.9'

services:
  bootnode:
    container_name: bootnode
    build: bootnode
    restart: on-failure
#    restart: always
    hostname: bootnode
#    links:
#      - netstats
#      - node
    entrypoint: /root/boot.sh
#    command: '--datadir=~/.ethereum/devchain --nodekeyhex=091bd6067cb4612df85d9c1ff85cc47f259ced4d4cd99816b14f35650f59c322 --rpcapi "db,personal,eth,net,web3" --rpccorsdomain="*" --networkid=456719 --rpc --rpcaddr="0.0.0.0"'
    volumes:
      - ./files/passwords:/root/files/passwords:ro
      - ./files/genesis.json:/root/files/genesis.json:ro
      - ./files/keystore:/root/node/bootnode/keystore:rw
#      - /etc/localtime:/etc/localtime:ro
      - ./node_data:/root/node:rw
    ports:
      - "31513:31513"
      - "31513:31513/udp"
      - "8545:8545"
#    stdin_open: true
#    tty: true

  node:
#    container_name: node
    build: node
    restart: on-failure
#    hostname: bootnode
#    links:
#      - netstats
#      - bootnode
    entrypoint: /root/start.sh
#    command: '--datadir=~/.ethereum/devchain --nodekeyhex=091bd6067cb4612df85d9c1ff85cc47f259ced4d4cd99816b14f35650f59c322 --rpcapi "db,personal,eth,net,web3" --rpccorsdomain="*" --networkid=456719 --rpc --rpcaddr="0.0.0.0"'
    volumes:
      - ./files/passwords:/root/files/passwords:ro
      - ./files/genesis.json:/root/files/genesis.json:ro
      - ./files/keystore:/root/files/keystore:rw
#      - /etc/localtime:/etc/localtime:ro
      - ./node_data:/root/node:rw
#    ports:
#      - "31513:31513"
#      - "31513:31513/udp"
#      - "8545:8545"


  netstats:
    image: settlemint/ethstats-server
#    build: eth-netstats
    restart: on-failure
    container_name: netstats
    hostname: netstats
    environment:
      - WS_SECRET=12345
#    volumes:
#      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"

volumes:
    node_data:
      driver: local

networks:
  default:
    driver: bridge
